services:

  # =========================
  # BACKEND - Laravel
  # =========================
  backend:
    container_name: slu_backend
    build:
      context: ./backend-laravel-api
    ports:
      - "8010:80"
    volumes:
      - ./backend-laravel-api:/var/www
    #  - ./backend-laravel-api/.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    networks:
      - slu-network

  # =========================
  # FRONTEND - React (Vite)
  # =========================
  frontend:
    container_name: slu_frontend
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
    networks:
      - slu-network

  # =========================
  # DATABASE - PostgreSQL
  # =========================
  db:
    container_name: slu_postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: controle_slu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - slu-network

  # =========================
  # PGADMIN (opcional)
  # =========================
  pgadmin:
    container_name: slu_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - slu-network

networks:
  slu-network:
    driver: bridge

volumes:
  db-data:
